on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install --no-interaction

      - name: Install Nuitka
        run: |
          poetry run python -m pip install nuitka

      - name: Build
        run: |
          poetry run python -m nuitka --standalone --onefile --follow-imports --enable-plugin=tk-inter --windows-disable-console -o ntpclock --assume-yes-for-downloads src/main.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            *.exe
            *.bin
